### ISSUE TITLE
git polling is done too often

### ISSUE THREAD

**Issue by montjoie** [GKernelCI/Gdocker#14]
It seems that git polling refresh is set to 10s, that's too short
buildbot_1    | 2021-02-15 11:30:41+0000 [-] gitpoller: processing changes from "https://github.com/gentoo/gentoo.git"
buildbot_1    | 2021-02-15 11:30:54+0000 [-] gitpoller: processing changes from "https://github.com/gentoo/gentoo.git"
buildbot_1    | 2021-02-15 11:31:01+0000 [-] gitpoller: processing changes from "https://github.com/gentoo/gentoo.git"
buildbot_1    | 2021-02-15 11:31:11+0000 [-] gitpoller: processing changes from "https://github.com/gentoo/gentoo.git"
buildbot_1    | 2021-02-15 11:31:22+0000 [-] gitpoller: processing changes from "https://github.com/gentoo/gentoo.git"
buildbot_1    | 2021-02-15 11:31:29+0000 [-] GitHubPullrequestPoller: polling GitHub repository gentoo/gentoo, branches: None
buildbot_1    | 2021-02-15 11:31:29+0000 [-] GitHubPullrequestPoller error 403 'API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)' while loading https://api.github.com/repos/gentoo/gentoo/pulls

**Comment by mjeveritt** [comment]
30s is plenty .. seriously, if we get more than 1 commit a minute (except for mass changes) we got other problems....

**Comment by aliceinwire** [comment]
fixed by https://github.com/GKernelCI/GBuildbot/commit/745c8866534e56d8ebcca5df748c2af64275febf
